// GENERATED by tools/build-global-extension.js — do not edit here.
// Source of truth: extension/*.ts + lib/session-utils.ts   Rebuild: npm run sync:extension
//
// Office Extension — global Pi telemetry bridge to the ORCA24 office hub.
// Sends machine identity, and redacts tool payloads whenever the hub is not loopback.
// Install on another machine: pi install npm:pi-office

export const OFFICE_EXTENSION_VERSION = '1.2.0';
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

// Stand down when a project ships its own copy of this extension, so Pi never
// registers office_set_task twice or double-posts one session.
function hasProjectLocalOfficeExtension(): boolean {
  try {
    let dir = path.resolve(process.cwd());
    while (true) {
      for (const name of ['index.ts', 'index.js']) {
        if (fs.existsSync(path.join(dir, '.pi', 'extensions', 'pi-office', name))) return true;
      }
      const parent = path.dirname(dir);
      if (parent === dir) return false;
      dir = parent;
    }
  } catch {
    return false;
  }
}
// Same problem across install methods: a machine can carry the file-based global copy
// (~/.pi/agent/extensions/pi-office.ts) AND a packaged copy (npm: install, git: clone, or a
// local path) at the same time. Pi loads both into one process, so the LLM would see two
// office_set_task tools and the office would get every event twice.
//
// Deliberately NOT a globalThis "already loaded" marker: that breaks /reload, which
// re-evaluates the module in the same process — the reloaded copy would see its own stale
// marker and stand down, killing telemetry silently until restart. Resolve the conflict from
// disk state instead, identical on first load and on reload: the explicit file copy wins,
// because it is the one npm run sync:extension publishes from source. A fresh laptop has no
// file copy, so the package is the only instance and loads normally.
function officeExtensionShouldDeferToOtherCopy(): boolean {
  try {
    const home = process.env.HOME || process.env.USERPROFILE || os.homedir();
    const fileCopy = path.join(home, '.pi', 'agent', 'extensions', 'pi-office.ts');
    const self = new URL(import.meta.url).pathname;
    if (path.resolve(self) === path.resolve(fileCopy)) return false;
    if (!fs.existsSync(fileCopy)) return false;
    process.stderr.write('[pi-office] salinan global di ' + fileCopy + ' menang; salinan ini dilewati.\n');
    return true;
  } catch {
    // Fail-safe: if identity cannot be resolved, load normally rather than vanish silently.
    return false;
  }
}

// ─── lib/session-utils.ts ──────────────────────────────────────────
// ── Single source of truth for office utilities ────────────────────────
//
// Dipakai oleh TIGA konsumen:
//   1. extension/*.ts        → di-bundle ke extensions-global/pi-office.ts
//   2. server/src/db.js      → hub lokal (Turso)
//   3. tools/*.js            → skrip maintenance
//
// Kenapa satu file: fungsi-fungsi ini dulu diduplikasi antara extension dan
// server, lalu di-split separuh-separuh — hasilnya `roundCost is not defined`
// di server dan bundle extension global yang kehilangan definisi. Satu file,
// satu salinan, semua import dari sini.
//
// Aturan: TIDAK boleh ada dependensi ke DB, Pi runtime API, atau module lain.
// Hanya `node:fs`, `node:path`, dan `process.env` — supaya bisa di-inline ke
// bundle extension dan tetap jalan di server biasa.


// ── Pi session log readers ─────────────────────────────────────────────

/** Trim + collapse whitespace, truncate ke maxLength karakter. */
function summarizePrompt(prompt: string, maxLength = 80): string {
  const clean = prompt.trim().replace(/\s+/g, ' ');
  return clean.length > maxLength ? clean.slice(0, maxLength - 3) + '...' : clean;
}

/** Root direktori session logs Pi CLI. */
function getPiSessionsRoot(): string {
  const home = process.env.HOME || process.env.USERPROFILE || '';
  return process.env.PI_SESSIONS_DIR || path.join(home, '.pi', 'agent', 'sessions');
}

/** Encode cwd jadi nama folder aman di bawah Pi sessions root. */
function encodeCwdForPiSessions(cwd: string): string {
  return `--${path.resolve(cwd).replace(/^\/+/, '').replace(/\/+$/g, '').replace(/\/+/g, '-')}--`;
}

/** File JSONL session log, terbaru dulu, dibatasi 50. */
function getSessionLogFiles(cwd: string, sessionId: string | null = null): string[] {
  const root = getPiSessionsRoot();
  const primaryDir = path.join(root, encodeCwdForPiSessions(cwd));
  const dirs: string[] = fs.existsSync(primaryDir)
    ? [primaryDir]
    : fs.existsSync(root)
      ? fs.readdirSync(root)
        .filter((entry) => entry.startsWith('--'))
        .map((entry) => path.join(root, entry))
      : [];

  const files = dirs.flatMap((dir) => {
    try {
      return fs.readdirSync(dir)
        .filter((file) => file.endsWith('.jsonl'))
        .map((file) => path.join(dir, file));
    } catch {
      return [];
    }
  });

  const scoped = sessionId
    ? files.filter((file) => path.basename(file).includes(sessionId))
    : files;

  return scoped
    .map((file) => ({ file, mtimeMs: fs.statSync(file).mtimeMs }))
    .sort((a, b) => b.mtimeMs - a.mtimeMs)
    .slice(0, 50)
    .map(({ file }) => file);
}

/** Teks murni dari content field pesan (string | block[]). */
function extractTextContent(content: any): string {
  if (typeof content === 'string') return content;
  if (!Array.isArray(content)) return '';
  return content
    .map((item) => {
      if (typeof item === 'string') return item;
      if (item?.type === 'text' && typeof item.text === 'string') return item.text;
      return '';
    })
    .filter(Boolean)
    .join('\n');
}

/** Prompt user terakhir dari session log — fallback untuk task. Fail-safe. */
function getLastPiCliPrompt(cwd: string, sessionId: string | null = null): string | null {
  try {
    for (const file of getSessionLogFiles(cwd, sessionId)) {
      const lines = fs.readFileSync(file, 'utf8').trim().split('\n').reverse();
      for (const line of lines) {
        try {
          const event = JSON.parse(line);
          if (event?.type !== 'message' || event?.message?.role !== 'user') continue;
          const prompt = extractTextContent(event.message.content).trim();
          if (prompt) return summarizePrompt(prompt);
        } catch { /* baris JSONL yang masih ditulis — skip */ }
      }
    }
  } catch { /* jangan pernah blok startup Pi CLI */ }
  return null;
}

/** Penanda task placeholder: server akan ganti dengan prompt asli. */
function isWaitingPromptTask(task: unknown): boolean {
  return typeof task === 'string' && /menunggu\s+prompt/i.test(task);
}

// ── Project identity ───────────────────────────────────────────────────

const projectNameCache = new Map<string, string | null>();
const PROJECT_ROOT_SEARCH_LIMIT = 12;

/**
 * Nama proyek: jalan naik dari cwd ke `.git` terdekat, supaya sesi yang mulai
 * di subdirektori tetap tercatat ke repo-nya, bukan ke `src/`. Dilewati kalau
 * path tidak ada di mesin ini (worktree SSH melaporkan path remote).
 */
function projectNameFromCwd(cwd: string): string | null {
  if (typeof cwd !== 'string' || !cwd.trim()) return null;
  const key = cwd.trim();
  if (projectNameCache.has(key)) return projectNameCache.get(key) ?? null;

  const isAbsolute = /^([a-zA-Z]:[\\/]|[\\/])/.test(key);
  const basenameOf = (p: string) => {
    const last = p.split(/[\\/]+/).filter(Boolean).pop() ?? '';
    return last.endsWith('.git') ? last.slice(0, -4) : last;
  };

  let name = basenameOf(key);
  if (isAbsolute && fs.existsSync(key)) {
    try {
      let dir = path.resolve(key);
      for (let depth = 0; depth < PROJECT_ROOT_SEARCH_LIMIT; depth += 1) {
        if (fs.existsSync(path.join(dir, '.git'))) {
          name = basenameOf(dir) || name;
          break;
        }
        const parent = path.dirname(dir);
        if (parent === dir) break;
        dir = parent;
      }
    } catch { /* fail-safe */ }
  }
  projectNameCache.set(key, name || null);
  return name || null;
}

// ── Machine identity ───────────────────────────────────────────────────

/** Path file machine-id, sama dengan yang ditulis extension. */
function officeMachineIdFile(): string {
  const home = process.env.HOME || process.env.USERPROFILE || '';
  return process.env.OFFICE_MACHINE_ID_FILE || path.join(home, '.pi', 'office', 'machine-id');
}

/**
 * Machine-id milik mesin ini, read-only (tidak membuat file).
 *
 * Dibutuhkan hub supaya reaper bisa membedakan "proses ini sudah mati" dari
 * "pid ini milik mesin lain". Setelah kantor memakai satu Turso bersama, semua
 * sesi hidup di tabel yang sama, sementara `/proc/<pid>` hanya berlaku untuk
 * mesin tempat hub berjalan.
 */
function readLocalMachineId(): string | null {
  const explicit = (process.env.OFFICE_MACHINE_ID || '').trim();
  if (explicit) return explicit;
  try {
    const value = fs.readFileSync(officeMachineIdFile(), 'utf8').trim();
    return value || null;
  } catch {
    return null;
  }
}

// ── Formatting helpers ─────────────────────────────────────────────────

/** Bulatkan biaya ke 8 desimal — cukup untuk USD fraksional, hindari float noise. */
function roundCost(value: unknown): number {
  return Math.round((Number(value) || 0) * 1e8) / 1e8;
}

/** Potong dari DEPAN — sisa teks menunjukkan bagian terbaru. */
function tailText(text: string, maxLength = 180): string {
  const clean = text.trim().replace(/\s+/g, ' ');
  return clean.length > maxLength ? '…' + clean.slice(clean.length - maxLength + 1) : clean;
}

/** Teks terlihat dari pesan assistant (blok `type: 'text'` saja). */
function extractAssistantVisibleText(message: any): string {
  if (!Array.isArray(message?.content)) return '';
  return message.content
    .filter((item: any) => item?.type === 'text' && typeof item.text === 'string')
    .map((item: any) => item.text)
    .join(' ')
    .trim();
}

/** Nama tool call dari event stream Pi (beberapa bentuk payload). */
function extractToolCallName(event: any): string | null {
  const update = event?.assistantMessageEvent;
  if (typeof update?.toolCall?.name === 'string') return update.toolCall.name;

  const idx = update?.contentIndex;
  const block = Number.isInteger(idx) ? update?.partial?.content?.[idx] || event?.message?.content?.[idx] : null;
  return typeof block?.name === 'string' ? block.name : null;
}

// ─── redact.ts ─────────────────────────────────────────────────────
// Redaction layer for office telemetry.
//
// Why: the office hub can be a public endpoint (Cloudflare Worker + Turso). Pi tool
// inputs carry file contents and shell commands, and tool results carry whatever those
// commands printed — including secrets read from .env. Once a row lands in the shared
// DB it is durable, so the only safe place to strip it is before it leaves the machine.
//
// Loopback hubs keep full detail (local dashboard stays useful); anything else is
// reduced to what an observer needs to watch work happen, not what was written.

const SECRET_PATTERNS: Array<[RegExp, string]> = [
  [/-----BEGIN [A-Z0-9 ]*PRIVATE KEY-----[\s\S]*?(-----END [A-Z0-9 ]*PRIVATE KEY-----|$)/g, '[redacted:key]'],
  [/\beyJ[A-Za-z0-9_-]{4,}\.[A-Za-z0-9_-]{4,}\.[A-Za-z0-9_-]{4,}\b/g, '[redacted:jwt]'],
  [/\bAKIA[0-9A-Z]{16}\b/g, '[redacted:aws]'],
  [/\b(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{16,}\b/g, '[redacted:gh]'],
  [/\bxox[baprs]-[A-Za-z0-9-]{10,}\b/g, '[redacted:slack]'],
  [/\bsk-[A-Za-z0-9_-]{20,}\b/g, '[redacted:apikey]'],
  [/((?:[A-Za-z0-9_]*(?:SECRET|TOKEN|PASSWORD|PASSWD|PASS|PWD|API_?KEY|ACCESS_KEY|PRIVATE_KEY|KEY|CREDENTIAL|AUTH|DSN)[A-Za-z0-9_]*|KEY)\s*[=:]\s*)["']?[^\s"',;]{4,}["']?/gi, '$1[redacted]'],
  [/(:\/\/)([^:/@\s]+):([^@/\s]+)@/g, '$1$2:[redacted]@'],
];

function redactSecrets(value: string): string {
  let out = value;
  for (const [pattern, replacement] of SECRET_PATTERNS) {
    out = out.replace(pattern, replacement);
  }
  return out;
}

function clip(value: string, maxLength: number): string {
  const clean = value.replace(/\s+/g, ' ').trim();
  return clean.length > maxLength ? clean.slice(0, Math.max(0, maxLength - 1)) + '…' : clean;
}

/**
 * Yang boleh dilihat observer di feed: SATU KATA KERJA. Bukan perintahnya.
 *
 * Kenapa seketat ini: command shell adalah kanal bocor paling lebar yang kita punya.
 * Di dalamnya ada path internal, nama service, flag kredensial, dan host — dan feed
 * office sengaja ditampilkan ke banyak orang. Regex saja tidak cukup karena nilai
 * kredensial sering lewat sebagai argumen POSISI (`curl -H "Authorization: Bearer …"`),
 * bukan sebagai `KEY=value`. Yang dikirim karena itu cuma maksud aksinya: `cd`, `git`,
 * `npm`, `curl`.
 *
 * Sengaja TANPA subcommand: `git commit` vs `git push --force` memang informatif, tapi
 * di sanalah argumen mulai ikut-ikutan (nama branch, URL, path). Satu token tidak.
 */
const COMMAND_WRAPPERS = new Set(['timeout', 'sudo', 'env', 'nohup', 'setsid', 'time', 'nice', 'doas']);

function commandVerb(command: string): string {
  const firstSegment = redactSecrets(command).split(/[;&|\n]+/)[0] || '';
  const tokens = firstSegment.trim().split(/\s+/).filter(Boolean).filter((token) => !token.startsWith('-'));
  let index = 0;
  while (index < tokens.length && COMMAND_WRAPPERS.has(tokens[index])) {
    // `timeout 90 node …` / `sudo -u x systemctl …`: lewati pembungkus dan angkanya.
    index += 1;
    while (index < tokens.length && /^[\d.]+[smh]?$/.test(tokens[index])) index += 1;
  }
  return tokens[index] || clip(firstSegment, 20);
}

/** @deprecated pakai commandVerb(); dipertahankan untuk pembacaan hasil audit lama. */
function sanitizeCommand(command: string, maxTokens = 1): string {
  return commandVerb(command);
}

function isLoopbackEndpoint(endpoint: string): boolean {
  try {
    const host = new URL(endpoint).hostname;
    return host === 'localhost' || host === '127.0.0.1' || host === '::1' || host === '[::1]' || host === '0.0.0.0';
  } catch {
    return false;
  }
}

/** Basename saja: `a/b/c.ts` → `c.ts`. Path penuh tidak keluar mesin. */
function pathBasename(value: string): string {
  const clean = redactSecrets(String(value || '')).trim();
  if (!clean) return '';
  const parts = clean.split(/[\\/]+/).filter(Boolean);
  return clip(parts[parts.length - 1] || clean, 60);
}

// Only these keys survive for a given tool. Anything not listed is dropped, so a new
// tool that takes a body-sized argument cannot widen the leak by accident.
const TOOL_ALLOWLIST: Record<string, string[]> = {
  bash: ['command', 'timeout'],
  read: ['path', 'offset', 'limit'],
  write: ['path'],
  edit: ['path'],
  grep: ['pattern', 'path', 'glob'],
  find: ['pattern', 'path'],
  ls: ['path'],
  subagent: ['agent', 'task', 'workflowScriptPath', 'workflow'],
  web_search: ['query'],
};

function summarizeToolInput(
  toolName: string,
  input: Record<string, any> | undefined
): Record<string, unknown> {
  if (!input || typeof input !== 'object') return {};
  const allowed = TOOL_ALLOWLIST[toolName] ?? Object.keys(input).slice(0, 6);
  const summary: Record<string, unknown> = {};

  for (const key of allowed) {
    const value = input[key];
    if (typeof value === 'string') {
      // `command` dan `path` adalah dua field yang paling banyak membocorkan struktur
      // dalam mesin: perintah dipangkas ke satu kata kerja, path ke basename saja
      // (masih cukup untuk "dia sedang mengerjakan redact.ts", tanpa /home/…/PROJEK).
      if (key === 'command') summary[key] = commandVerb(value);
      else if (key === 'path' || key === 'workflowScriptPath') summary[key] = pathBasename(value);
      else summary[key] = clip(redactSecrets(value), 120);
    } else if (typeof value === 'number' || typeof value === 'boolean') {
      summary[key] = value;
    }
  }

  // Keep the shape visible without shipping the payload.
  const dropped = Object.keys(input).filter((key) => !allowed.includes(key));
  if (dropped.length) summary._omitted = dropped.slice(0, 8);
  return summary;
}

function redactStrings(value: unknown, depth = 0): unknown {
  if (depth > 4) return undefined;
  if (typeof value === 'string') return clip(redactSecrets(value), 200);
  if (typeof value === 'number' || typeof value === 'boolean' || value === null) return value;
  if (Array.isArray(value)) return value.slice(0, 12).map((item) => redactStrings(item, depth + 1));
  if (typeof value === 'object') {
    const out: Record<string, unknown> = {};
    for (const [key, item] of Object.entries(value as Record<string, unknown>).slice(0, 16)) {
      out[key] = redactStrings(item, depth + 1);
    }
    return out;
  }
  return undefined;
}

/**
 * Reduce one telemetry event to what is safe to publish to a shared hub.
 * Unknown event types fall back to a redacted deep-clone rather than a passthrough:
 * forgetting to register a new event type must fail closed.
 */
function sanitizeEvent(type: string, payload: Record<string, any>): Record<string, any> {
  const out: Record<string, any> = { ...payload };

  switch (type) {
    case 'tool.call': {
      out.input = summarizeToolInput(String(payload.tool_name || ''), payload.input);
      break;
    }
    case 'tool.result': {
      const details = payload.result ?? payload.details;
      const text = typeof details === 'string' ? details : details === undefined ? '' : JSON.stringify(details);
      delete out.result;
      delete out.details;
      out.output_chars = text.length;
      break;
    }
    case 'llm.stream': {
      out.text = clip(redactSecrets(String(payload.text || '')), 140);
      break;
    }
    case 'task.update':
    case 'session.register':
    case 'session.heartbeat':
    case 'team.register': {
      if (typeof out.task === 'string') out.task = clip(redactSecrets(out.task), 100);
      if (typeof out.name === 'string') out.name = clip(redactSecrets(out.name), 80);
      if (typeof out.parent_name === 'string') out.parent_name = clip(redactSecrets(out.parent_name), 80);
      break;
    }
    case 'log.append': {
      out.message = clip(redactSecrets(String(payload.message || '')), 200);
      break;
    }
    default: {
      return (redactStrings(payload) as Record<string, any>) ?? {};
    }
  }

  return out;
}

// ─── config.ts ─────────────────────────────────────────────────────
type OfficeExtensionConfig = {
  url?: string;
  endpoint?: string;
  token?: string;
  enabled?: boolean;
  machineId?: string;
  machineName?: string;
  orcaName?: string;
  orcaWorkspace?: string;
  orcaPane?: string;
};

/**
 * Office default when a machine has no config at all.
 *
 * Why cloud-first: a fresh `pi install npm:pi-office` on another laptop has no
 * ~/.pi/office/config.json, and the old loopback fallback meant it silently posted to a hub
 * that does not exist there. Pointing at the deployed Worker makes the package work with zero
 * setup for a member of this office. A stranger's install just gets a 401 and no telemetry —
 * the token is what gates writes, not the URL.
 */
const DEFAULT_CLOUD_ENDPOINT = 'https://pi-office.hanirizo.workers.dev/api/event';
const DEFAULT_LOCAL_ENDPOINT = 'http://127.0.0.1:4317/api/event';

function officeDir(): string {
  return path.join(process.env.HOME || process.env.USERPROFILE || os.homedir(), '.pi', 'office');
}

function officeConfigPath(): string {
  return path.join(officeDir(), 'config.json');
}

function parseJson(file: string): OfficeExtensionConfig | null {
  try {
    return JSON.parse(fs.readFileSync(file, 'utf8')) as OfficeExtensionConfig;
  } catch {
    return null;
  }
}

/** Raw config, ignoring the `enabled` switch. Needed by `/office on` to read a saved token. */
function readRawOfficeConfig(): OfficeExtensionConfig | null {
  return parseJson(officeConfigPath()) ?? parseJson(path.join(officeDir(), 'orca.json'));
}

function readOfficeExtensionConfig(): OfficeExtensionConfig | null {
  // config.json is owned by the Pi extension; orca.json remains a backwards-compatible
  // bridge config so existing Orca installs keep working.
  const config = readRawOfficeConfig();
  return !config || config.enabled === false ? null : config;
}

/**
 * Telemetry opt-out. Distinct from readOfficeExtensionConfig(), which returns null when
 * disabled and would otherwise be read as "no config at all → use the packaged cloud
 * default". `enabled: false` must mean silent, not "report somewhere else".
 */
function officeTelemetryEnabled(): boolean {
  if (process.env.OFFICE_DISABLED) return false;
  return readRawOfficeConfig()?.enabled !== false;
}

/** Merge into the extension-owned config file. Mode 0600 — this file can carry a bearer token. */
function writeOfficeExtensionConfig(patch: Partial<OfficeExtensionConfig>): OfficeExtensionConfig {
  const file = officeConfigPath();
  const next = { ...(readRawOfficeConfig() ?? {}), ...patch };
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(next, null, 2) + '\n', { mode: 0o600 });
  return next;
}

function officeEventEndpoint(config = readOfficeExtensionConfig()): string {
  // `OFFICE_LOCAL=1` is the developer switch: run against a hub on this machine without
  // editing (or losing) a cloud config.
  if (process.env.OFFICE_ENDPOINT) return process.env.OFFICE_ENDPOINT;
  if (process.env.OFFICE_LOCAL) return DEFAULT_LOCAL_ENDPOINT;
  if (config?.endpoint) return config.endpoint;
  if (config?.url) {
    try {
      return `${new URL(config.url).origin}/api/event`;
    } catch {
      // Fall through to the packaged default.
    }
  }
  return DEFAULT_CLOUD_ENDPOINT;
}

/** Dashboard origin for the same hub, e.g. `https://pi-office.hanirizo.workers.dev`. */
function officeHubOrigin(endpoint = officeEventEndpoint()): string | null {
  try {
    return new URL(endpoint).origin;
  } catch {
    return null;
  }
}

// ─── identity.ts ───────────────────────────────────────────────────
type OfficeClientKind = 'pi' | 'orca' | 'subagent';

interface OfficeClientIdentity {
  machine_id: string;
  machine_name: string;
  orca_name?: string;
  orca_workspace?: string;
  orca_pane?: string;
  client_kind: OfficeClientKind;
}

const MACHINE_ID_PREFIX = 'office-machine-';

function clean(value: unknown, maxLength = 120): string | undefined {
  if (typeof value !== 'string') return undefined;
  const normalized = value.trim().replace(/\s+/g, ' ');
  return normalized ? normalized.slice(0, maxLength) : undefined;
}

// Path file-nya satu sumber dengan hub (lib/session-utils.ts): hub membaca file yang sama
// untuk membatasi reaper, jadi kalau dua-duanya punya definisi sendiri, suatu hari cukup
// satu perubahan nama file untuk membuat reaper salah melihat sesi.
const machineIdFile = officeMachineIdFile;

function fallbackMachineId(): string {
  const raw = `${os.hostname()}|${os.platform()}|${os.arch()}`;
  return MACHINE_ID_PREFIX + crypto.createHash('sha256').update(raw).digest('hex').slice(0, 16);
}

function stableMachineId(): string {
  const config = readOfficeExtensionConfig();
  const explicit = clean(process.env.OFFICE_MACHINE_ID, 160) || clean(config?.machineId, 160);
  if (explicit) return explicit;

  const file = machineIdFile();
  try {
    const existing = clean(fs.readFileSync(file, 'utf8'), 160);
    if (existing) return existing;
  } catch {
    // The identity file is a convenience; fallback below keeps telemetry alive.
  }

  const generated = MACHINE_ID_PREFIX + crypto.randomUUID();
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, `${generated}\n`, { flag: 'wx', mode: 0o600 });
    return generated;
  } catch {
    return fallbackMachineId();
  }
}

function getOfficeClientIdentity(clientKind: OfficeClientKind): OfficeClientIdentity {
  const config = readOfficeExtensionConfig();
  const machineName =
    clean(process.env.OFFICE_MACHINE_NAME) ||
    clean(config?.machineName) ||
    clean(os.hostname()) ||
    'unknown-device';

  return {
    machine_id: stableMachineId(),
    machine_name: machineName,
    orca_name: clean(process.env.OFFICE_ORCA_NAME) || clean(process.env.ORCA_NAME) || clean(config?.orcaName),
    orca_workspace:
      clean(process.env.OFFICE_ORCA_WORKSPACE) ||
      clean(process.env.ORCA_WORKSPACE_NAME) ||
      clean(process.env.ORCA_WORKSPACE) ||
      clean(config?.orcaWorkspace),
    orca_pane: clean(process.env.OFFICE_ORCA_PANE) || clean(process.env.ORCA_PANE_KEY) || clean(config?.orcaPane),
    client_kind: clientKind
  };
}

// ─── client.ts ─────────────────────────────────────────────────────
const SEND_TIMEOUT_MS = 1200;

let CONFIG = readOfficeExtensionConfig();
let ENDPOINT = officeEventEndpoint(CONFIG);
let OFFICE_TOKEN = process.env.OFFICE_TOKEN || CONFIG?.token || '';
let ENABLED = officeTelemetryEnabled();

// Keputusan sensor TIDAK boleh lagi bergantung pada "hop pertama loopback".
// Sejak hub lokal menulis ke Turso/cloud, `http://127.0.0.1:4317` tetap berarti detail
// penuh tersimpan di database bersama — dan baris itu permanen. Jadi yang ditanya adalah
// tempat datanya DIDARAT, dan hanya hub yang tahu itu: dia melaporkannya lewat
// GET /api/health → `storage`. Gagal probe / jawaban tak dikenal = tetap men-sensor
// (fail-closed), bukan membuka.
let REDACT = true;
let hubStorage = 'unknown';
let storageProbed = false;
let lastError = '';
let lastSentAt = 0;

/** Tanya hub tempat datanya didarat. Panggil sebelum event pertama; jangan pernah blok. */
export async function probeHubStorage(): Promise<string> {
  if (storageProbed && !process.env.OFFICE_ENDPOINT) return hubStorage;
  storageProbed = true;
  try {
    const origin = new URL(ENDPOINT).origin;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), 900);
    const headers: Record<string, string> = {};
    if (OFFICE_TOKEN) headers.Authorization = `Bearer ${OFFICE_TOKEN}`;
    const res = await fetch(`${origin}/api/health`, { headers, signal: controller.signal });
    clearTimeout(timer);
    if (!res.ok) return hubStorage;
    const body = (await res.json()) as { storage?: string };
    hubStorage = typeof body?.storage === 'string' ? body.storage : 'unknown';
    REDACT = hubStorage !== 'local-file';
  } catch {
    // Fail-closed: hub tak dikenal berarti sensor menyala.
  }
  return hubStorage;
}


/**
 * Re-resolve endpoint/token after ~/.pi/office/config.json changes, so `/office connect`
 * takes effect in the running session instead of only after a Pi restart.
 */
function refreshOfficeConfig(): void {
  CONFIG = readOfficeExtensionConfig();
  ENDPOINT = officeEventEndpoint(CONFIG);
  OFFICE_TOKEN = process.env.OFFICE_TOKEN || CONFIG?.token || '';
  ENABLED = officeTelemetryEnabled();
  storageProbed = false;
  hubStorage = 'unknown';
  REDACT = true;
}

function officeTelemetryTarget(): { endpoint: string; redacting: boolean; authed: boolean; enabled: boolean; hubStorage: string; lastError: string; lastSentAt: number } {
  return { endpoint: ENDPOINT, redacting: REDACT, authed: Boolean(OFFICE_TOKEN), enabled: ENABLED, hubStorage, lastError, lastSentAt };
}

export async function sendOfficeEvent(type: string, payload: Record<string, any>): Promise<boolean> {
  // `enabled: false` means this machine opted out — not "send to the default hub instead".
  if (!ENABLED) return false;
  try {
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), SEND_TIMEOUT_MS);

    const headers: Record<string, string> = { 'Content-Type': 'application/json' };
    if (OFFICE_TOKEN) headers.Authorization = `Bearer ${OFFICE_TOKEN}`;

    const res = await fetch(ENDPOINT, {
      method: 'POST',
      headers,
      body: JSON.stringify({ type, payload: REDACT ? sanitizeEvent(type, payload) : payload }),
      signal: controller.signal
    });

    clearTimeout(timeout);
    if (!res.ok) {
      lastError = `HTTP ${res.status}`;
      return false;
    }
    lastError = '';
    lastSentAt = Date.now();
    return true;
  } catch (err: any) {
    // Fail-safe: never crash or block Pi CLI
    lastError = err?.name === 'AbortError' ? `timeout ${SEND_TIMEOUT_MS}ms` : String(err?.message || err);
    return false;
  }
}

// ─── indonesian-names.ts ───────────────────────────────────────────
interface OfficePersona {
  name: string;
  role: string;
  avatar: string;
  color: string;
}

// 100 reserved office personas — 80% female by design (80 female / 20 male).
// Names mix Indonesian and international first names (Saarah, Clara, Camille, …).
// Names are intentionally unique so the office avoids obvious duplicate display
// names across many concurrent Pi sessions. The session suffix still remains as a
// hard uniqueness guard.
//
// Avatar rule: female personas use 👩-family / 🧕 / 👸 / 🙋‍♀️ glyphs and male personas
// use 👨-family / 🧔 glyphs, so the 3D engine can infer gender from the avatar alone.
// `inferAgentGender()` in the dashboard keeps a first-name list as fallback.
const PERSONAS: OfficePersona[] = [
  // ── Female (80) ───────────────────────────────────────────────────────────
  { name: 'Saarah', role: 'Principal Architect · System Design', avatar: '👩‍🚀', color: '#6366f1' },
  { name: 'Clara', role: 'Frontend Engineer · React & State Sync', avatar: '👩‍💻', color: '#22d3ee' },
  { name: 'Camille', role: 'Design Systems · Tokens & Motion', avatar: '👩‍🎨', color: '#ec4899' },
  { name: 'Amara', role: 'Product Strategist · Backlog & Sprint', avatar: '👩‍💼', color: '#a855f7' },
  { name: 'Nadia', role: 'AI Integration · Model Tuning', avatar: '👩‍🔬', color: '#d946ef' },
  { name: 'Kirana', role: 'Data Engineer · Pipelines & ETL', avatar: '👩‍💻', color: '#15803d' },
  { name: 'Alya', role: 'Component Library · Accessibility', avatar: '👩‍🎨', color: '#be185d' },
  { name: 'Sinta', role: 'Content Engineer · Release Notes', avatar: '👩‍🏫', color: '#f97316' },
  { name: 'Maya', role: 'Research Engineer · Evaluation', avatar: '👩‍🔬', color: '#8b5cf6' },
  { name: 'Dewi', role: 'Frontend Architect · Rendering & SSR', avatar: '👩‍💻', color: '#f43f5e' },
  { name: 'Putri', role: 'Product Ops · Rituals & Reviews', avatar: '👩‍💼', color: '#16a34a' },
  { name: 'Intan', role: 'UX Researcher · User Flows', avatar: '👩‍💼', color: '#f472b6' },
  { name: 'Rani', role: 'Support Engineer · Triage & Tickets', avatar: '🙋‍♀️', color: '#ea580c' },
  { name: 'Sekar', role: 'UX Writer · Microcopy & I18N', avatar: '👩‍🏫', color: '#e11d48' },
  { name: 'Melati', role: 'Frontend Engineer · Components', avatar: '👩‍💻', color: '#fb7185' },
  { name: 'Wulan', role: 'Design Ops · Token Governance', avatar: '👩‍🎨', color: '#db2777' },
  { name: 'Tari', role: 'Visual Designer · 3D Office', avatar: '👩‍🎨', color: '#c026d3' },
  { name: 'Dinda', role: 'Analytics Engineer · Metrics', avatar: '👩‍💻', color: '#059669' },
  { name: 'Nabila', role: 'QA Engineer · Smoke Tests', avatar: '👩‍🔬', color: '#9333ea' },
  { name: 'Farah', role: 'Product Manager · Roadmap', avatar: '👩‍💼', color: '#65a30d' },
  { name: 'Salma', role: 'Security Engineer · Threat Models', avatar: '👩‍💻', color: '#dc2626' },
  { name: 'Zahra', role: 'Backend Engineer · Event Hub', avatar: '👩‍💻', color: '#4f46e5' },
  { name: 'Laila', role: 'Release Manager · Coordination', avatar: '👩‍💼', color: '#0d9488' },
  { name: 'Mira', role: 'Data Analyst · Insights', avatar: '👩‍💻', color: '#14b8a6' },
  { name: 'Ayu', role: 'Knowledge Engineer · Memory', avatar: '👩‍🏫', color: '#7c3aed' },
  { name: 'Novi', role: 'Release QA · Verification', avatar: '👩‍🔬', color: '#22c55e' },
  { name: 'Salsabila', role: 'Design Research · Prototypes', avatar: '👩‍🎨', color: '#e879f9' },
  { name: 'Yuni', role: 'Operations Analyst · Workflow', avatar: '👩‍💼', color: '#16a34a' },
  { name: 'Prita', role: 'Program Manager · Delivery', avatar: '👩‍💼', color: '#84cc16' },
  { name: 'Melly', role: 'Documentation Lead · Guides', avatar: '👩‍🏫', color: '#c084fc' },
  { name: 'Cahya', role: 'Visual QA · Layout & Contrast', avatar: '👩‍🔬', color: '#fb923c' },
  { name: 'Arumi', role: 'Interaction Engineer · Motion', avatar: '👩‍🎨', color: '#f59e0b' },
  { name: 'Mega', role: 'Frontend Lead · Dashboard', avatar: '👩‍💻', color: '#0ea5e9' },
  { name: 'Rossa', role: 'QA Lead · Test Strategy', avatar: '👩‍🔬', color: '#7c2d12' },
  { name: 'Tiara', role: 'Design Lead · Experience', avatar: '👩‍🎨', color: '#a21caf' },
  { name: 'Rika', role: 'QA Automation · Fixtures', avatar: '👩‍💻', color: '#8b5cf6' },
  { name: 'Mila', role: 'Product Analyst · Experiments', avatar: '👩‍💻', color: '#4ade80' },
  { name: 'Astri', role: 'Reliability Analyst · SLO & Uptime', avatar: '👩‍💼', color: '#10b981' },
  { name: 'Cempaka', role: 'UI Engineer · Visual Polish', avatar: '👩‍🎨', color: '#db2777' },
  { name: 'Larasati', role: 'Product Designer · Interaction', avatar: '👩‍🎨', color: '#f0abfc' },
  { name: 'Anisa', role: 'Design Systems · Figma Handoff', avatar: '👩‍🎨', color: '#f472b6' },
  { name: 'Citra', role: 'QA Analyst · Regression', avatar: '👩‍🔬', color: '#c084fc' },
  { name: 'Kenanga', role: 'Technical Writer · API Docs', avatar: '👩‍🏫', color: '#d97706' },
  { name: 'Tasya', role: 'Test Engineer · E2E Suites', avatar: '👩‍🔬', color: '#9333ea' },
  { name: 'Niken', role: 'Quality Engineer · Coverage', avatar: '👩‍🔬', color: '#a21caf' },
  { name: 'Fitri', role: 'Research Ops · Synthesis', avatar: '👩‍🔬', color: '#9333ea' },
  { name: 'Monica', role: 'Frontend Engineer · Forms', avatar: '👩‍💻', color: '#ec4899' },
  { name: 'Lina', role: 'Accessibility Engineer · ARIA', avatar: '👩‍💻', color: '#be185d' },
  { name: 'Bella', role: 'Customer Success · Adoption', avatar: '👩‍💼', color: '#65a30d' },
  { name: 'Reni', role: 'Data Product · Reporting', avatar: '👩‍💻', color: '#0f766e' },
  { name: 'Amira', role: 'Platform Engineer · Observability', avatar: '👩‍💻', color: '#06b6d4' },
  { name: 'Noor', role: 'Runtime Engineer · Agent Loop', avatar: '👩‍💻', color: '#2563eb' },
  { name: 'Elise', role: 'Performance Engineer · Latency & WebGL', avatar: '👩‍🔧', color: '#f59e0b' },
  { name: 'Freya', role: 'DevOps Specialist · Docker & CI/CD', avatar: '👩‍💻', color: '#3b82f6' },
  { name: 'Chloe', role: 'Realtime Engineer · WebSocket Hub', avatar: '👩‍💻', color: '#0369a1' },
  { name: 'Maeve', role: 'Systems Engineer · Cache & Storage', avatar: '👩‍🔧', color: '#0f766e' },
  { name: 'Lucia', role: 'Telemetry Engineer · Events', avatar: '👩‍💻', color: '#7dd3fc' },
  { name: 'Iris', role: 'Build Engineer · Bundling', avatar: '👩‍💻', color: '#0284c7' },
  { name: 'Hana', role: 'CLI Engineer · Commands', avatar: '👩‍💻', color: '#0ea5e9' },
  { name: 'Nina', role: 'Integration Engineer · Extensions', avatar: '👩‍💻', color: '#2563eb' },
  { name: 'Zoe', role: 'Tooling Engineer · Developer UX', avatar: '👩‍🔧', color: '#ea580c' },
  { name: 'Kira', role: 'Security Ops · Secrets', avatar: '👩‍💻', color: '#991b1b' },
  { name: 'Alina', role: 'Cloud Engineer · Networking', avatar: '👩‍💻', color: '#1d4ed8' },
  { name: 'Sena', role: 'Infrastructure Lead · Scaling', avatar: '👩‍🔧', color: '#64748b' },
  { name: 'Esme', role: 'Design Engineer · Storybook', avatar: '👩‍🎨', color: '#e11d48' },
  { name: 'Aruna', role: 'Data Reliability · Storage', avatar: '👩‍💻', color: '#4d7c0f' },
  { name: 'Kavya', role: 'Automation Engineer · Scripting', avatar: '👩‍🔧', color: '#0891b2' },
  { name: 'Selene', role: 'Sandbox Engineer · Isolation', avatar: '👩‍🚀', color: '#1e293b' },
  { name: 'Maira', role: 'Feedback Engineer · Customer Loop', avatar: '👩‍💼', color: '#0e7490' },
  { name: 'Anindya', role: 'Frontend Specialist · Charts', avatar: '👩‍💻', color: '#d946ef' },
  { name: 'Saras', role: 'Benchmark Engineer · Profiling', avatar: '👩‍🔬', color: '#ca8a04' },
  { name: 'Indira', role: 'Architecture Reviewer · Boundaries', avatar: '👩‍💼', color: '#0f766e' },
  { name: 'Kamila', role: 'Release Engineer · Rollouts', avatar: '👩‍💻', color: '#166534' },
  { name: 'Alea', role: 'Prompt Engineer · Instruction Tuning', avatar: '👩‍🔬', color: '#6d28d9' },
  { name: 'Rhea', role: 'Evaluation Engineer · Rubrics', avatar: '👩‍🔬', color: '#8b5cf6' },
  { name: 'Callista', role: 'API Engineer · Contracts', avatar: '👩‍💻', color: '#38bdf8' },
  { name: 'Anwita', role: 'Localization Engineer · ID/EN', avatar: '👩‍🏫', color: '#f97316' },
  { name: 'Vania', role: 'Sandbox QA · Fault Injection', avatar: '👩‍🔬', color: '#b91c1c' },
  { name: 'Nayla', role: 'Visual Engineer · Shaders', avatar: '👩‍🎨', color: '#c026d3' },
  { name: 'Aisyah', role: 'Studio Ops · Coffee Program', avatar: '👩‍🍳', color: '#92400e' },

  // ── Male (20) ─────────────────────────────────────────────────────────────
  { name: 'Budi Santoso', role: 'Backend Lead · API & Microservices', avatar: '🧔', color: '#6366f1' },
  { name: 'Rizky Pratama', role: 'DevOps Engineer · Pipelines & Runners', avatar: '👨‍💻', color: '#3b82f6' },
  { name: 'Ahmad Fauzi', role: 'Security Architect · Sandboxing & CSP', avatar: '👨‍🚒', color: '#ef4444' },
  { name: 'Bayu Saputra', role: 'Systems Engineer · Database & Cache', avatar: '👨‍💻', color: '#10b981' },
  { name: 'Dimas Wicaksono', role: 'Data Engineer · Analytics & ETL', avatar: '👨‍💻', color: '#14b8a6' },
  { name: 'Andi Wijaya', role: 'Runtime Engineer · Session Lifecycle', avatar: '👨‍💻', color: '#0ea5e9' },
  { name: 'Hendra Gunawan', role: 'Infrastructure Lead · Capacity Planning', avatar: '👨‍🔧', color: '#64748b' },
  { name: 'Teguh Setiawan', role: 'Database Engineer · SQLite & WAL', avatar: '👨‍💻', color: '#84cc16' },
  { name: 'Yoga Mahendra', role: 'API Engineer · REST & GraphQL', avatar: '👨‍💻', color: '#38bdf8' },
  { name: 'Arif Rahman', role: 'Security Engineer · AppSec & Audits', avatar: '👨‍🚒', color: '#dc2626' },
  { name: 'Naufal Hakim', role: 'Fullstack Engineer · Delivery', avatar: '👨‍💻', color: '#2563eb' },
  { name: 'Reza Maulana', role: 'Site Reliability · Health Checks', avatar: '👨‍🚀', color: '#7c3aed' },
  { name: 'Doni Kurniawan', role: 'Backend Engineer · Streams & Sinks', avatar: '🧔', color: '#4f46e5' },
  { name: 'Joko Priyanto', role: 'Systems Architect · Topology', avatar: '👨‍💼', color: '#059669' },
  { name: 'Rafi Hidayat', role: 'AI Product Engineer · Prompts', avatar: '👨‍💻', color: '#9333ea' },
  { name: 'Galih Prakoso', role: 'Build Engineer · Tree-shaking & Chunks', avatar: '👨‍🔧', color: '#0284c7' },
  { name: 'Yusuf Ramadhan', role: 'Cloud Engineer · Edge & DNS', avatar: '👨‍💻', color: '#1d4ed8' },
  { name: 'Rangga Aditya', role: 'Backend Engineer · Queues', avatar: '👨‍💻', color: '#0f766e' },
  { name: 'Bima Ardiansyah', role: 'Core Engineer · State Machine', avatar: '👨‍💻', color: '#2563eb' },
  { name: 'Satria Wibowo', role: 'Performance Lead · Runtime Cost', avatar: '👨‍💻', color: '#b45309' },
];

function getPersonaForSession(sessionId: string): OfficePersona {
  // Deterministic persona based on string hash of sessionId.
  // The base persona may repeat after the reserved pool is saturated; the public
  // display name below adds a session-derived suffix as a hard uniqueness guard.
  let hash = 0;
  for (let i = 0; i < sessionId.length; i++) {
    hash = (hash << 5) - hash + sessionId.charCodeAt(i);
    hash |= 0;
  }
  const index = Math.abs(hash) % PERSONAS.length;
  return PERSONAS[index];
}

function shortSessionSuffix(sessionId: string): string {
  const clean = String(sessionId || '')
    .replace(/[^a-zA-Z0-9]/g, '')
    .slice(-6);
  return clean || Math.random().toString(36).slice(2, 8);
}

function getSessionDisplayName(persona: OfficePersona, sessionId: string): string {
  return `${persona.name} · ${shortSessionSuffix(sessionId)}`;
}

// Sub-agents follow the same 80/20 female-majority split.
const SUBAGENT_PERSONAS: OfficePersona[] = [
  { name: 'Dara (Sub-Agent)', role: 'Code Refactoring Specialist', avatar: '👩‍💻', color: '#818cf8' },
  { name: 'Riri (Sub-Agent)', role: 'Unit Test Generator', avatar: '👩‍🔬', color: '#c084fc' },
  { name: 'Nana (Sub-Agent)', role: 'Dependency Audit Scout', avatar: '🙋‍♀️', color: '#38bdf8' },
  { name: 'Tita (Sub-Agent)', role: 'Schema & DDL Validator', avatar: '👩‍💻', color: '#4ade80' },
  { name: 'Hadi (Sub-Agent)', role: 'Benchmark & Profiler', avatar: '👨‍💻', color: '#fbbf24' },
];

function getSubagentPersona(subagentId: string): OfficePersona {
  let hash = 0;
  for (let i = 0; i < subagentId.length; i++) {
    hash = (hash << 5) - hash + subagentId.charCodeAt(i);
    hash |= 0;
  }
  const index = Math.abs(hash) % SUBAGENT_PERSONAS.length;
  return SUBAGENT_PERSONAS[index];
}

// ─── index.ts ──────────────────────────────────────────────────────
interface ToolEventPayload {
  toolName: string;
  toolCallId?: string;
  input?: Record<string, any>;
  details?: any;
  isError?: boolean;
}

function officeExtension(pi: any) {
  if (hasProjectLocalOfficeExtension() || officeExtensionShouldDeferToOtherCopy()) return;
  let currentSessionId = 'sesi_' + Math.random().toString(36).slice(2, 8);
  let currentPersona = getPersonaForSession(currentSessionId);
  let currentDisplayName = getSessionDisplayName(currentPersona, currentSessionId);
  let currentTask = getLastPiCliPrompt(process.cwd(), currentSessionId) || 'Belum ada prompt Pi CLI';
  let currentModel = 'pi-model';
  let liveResponseText = '';
  let liveThinkingChars = 0;
  let lastStreamSentAt = 0;
  let onboardingHintShown = false;
  const activeToolCalls = new Map<string, number>();
  const clientIdentity = getOfficeClientIdentity('pi');

  async function publishLlmStream(kind: 'response' | 'thinking' | 'tool' | 'status', text: string, isFinal = false, force = false) {
    const now = Date.now();
    if (!force && now - lastStreamSentAt < 180) return;
    lastStreamSentAt = now;

    await sendOfficeEvent('llm.stream', {
      session_id: currentSessionId,
      kind,
      text: tailText(text),
      is_final: isFinal
    });
  }

  // Tagihan: Pi sudah menghitung token + cost di setiap assistant message. Sekali kirim
  // per panggilan LLM — server yang merangkumnya jadi bill per pegawai & per menu.
  async function publishUsage(message: any) {
    const usage = message?.usage;
    const totalTokens = Number(usage?.totalTokens) || 0;
    if (!usage || totalTokens <= 0) return;

    const model = typeof message.model === 'string' && message.model ? message.model : currentModel;
    currentModel = model;

    await sendOfficeEvent('session.usage', {
      session_id: currentSessionId,
      model,
      provider: typeof message.provider === 'string' ? message.provider : null,
      input: Number(usage.input) || 0,
      output: Number(usage.output) || 0,
      cache_read: Number(usage.cacheRead) || 0,
      cache_write: Number(usage.cacheWrite) || 0,
      total_tokens: totalTokens,
      reported_cost: Number(usage.cost?.total) || 0,
      created_at: Number(message.timestamp) || Date.now()
    });
  }

  // 1. Hook: session_start
  pi.on('session_start', async (_event: any, ctx: any) => {
    try {
      // Tempat data didarat menentukan seberapa detail boleh keluar, jadi tanyakan SEBELUM
      // event pertama. Fail-closed: kalau probe gagal, sensor tetap menyala.
      await probeHubStorage();
      const sm = ctx?.sessionManager;
      const sId = sm?.getSessionId?.();
      if (typeof sId === 'string' && sId) {
        currentSessionId = sId;
        currentPersona = getPersonaForSession(currentSessionId);
        currentDisplayName = getSessionDisplayName(currentPersona, currentSessionId);
      }

      // NAMA SESI = satu sumber kebenaran untuk footer Pi DAN office.
      // Ekstensi ini dulunya auto-set nama ber-prefix emoji avatar (mis. "👩‍🔬 Vania · 5acb17").
      // Itu membuat footer Pi (yang ikut emoji) tidak sama dengan office (yang tampil avatar terpisah).
      // Aturan sekarang:
      //   - Kalau user sudah set nama sendiri via /name (tidak ber-emoji avatar di depan) -> hormati itu.
      //   - Kalau nama masih ber-emoji avatar (auto dari ekstensi lama) -> gunakan nama persona kantor
      //     tanpa emoji, supaya identik dengan yang dikirim ke office.
      const rawName = pi.getSessionName?.();
      const looksLikeAutoName =
        typeof rawName === 'string' &&
        /^[\u{1F000}-\u{1FAFF}\u{2600}-\u{27BF}\u{2190}-\u{21FF}\u{2B00}-\u{2BFF}]/u.test(rawName.trim());
      const resolvedName =
        typeof rawName === 'string' && rawName.trim() && !looksLikeAutoName
          ? rawName.trim()
          : currentDisplayName;
      currentDisplayName = resolvedName;

      if (typeof pi.setSessionName === 'function') {
        pi.setSessionName(resolvedName);
      }

      const cwd = ctx?.cwd || process.cwd();
      currentTask = getLastPiCliPrompt(cwd, currentSessionId) || currentTask;
      if (typeof ctx?.model?.id === 'string' && ctx.model.id) {
        currentModel = ctx.model.id;
      }

      await sendOfficeEvent('session.register', {
        session_id: currentSessionId,
        name: currentDisplayName,
        role: currentPersona.role,
        avatar: currentPersona.avatar,
        color: currentPersona.color,
        cwd,
        model: ctx?.model?.id || 'pi-model',
        pid: process.pid,
        task: currentTask,
        is_subagent: 0,
        ...clientIdentity
      });

      // A remote hub without a token answers 401, which is otherwise invisible: every
      // sendOfficeEvent() swallows its error by design. Say it out loud once per session.
      if (!onboardingHintShown) {
        const target = officeTelemetryTarget();
        if (!target.authed && !target.endpoint.includes('127.0.0.1')) {
          onboardingHintShown = true;
          ctx?.ui?.notify?.(`☕ Kantor butuh token — jalankan /office connect <token>. Target: ${target.endpoint}`, 'info');
        }
      }
    } catch {
      // safe fallback
    }
  });

  // 2. Hook: before_agent_start -> Tangkap PROMPT ASLI yang diketik user sebagai TASK!
  pi.on('before_agent_start', async (event: any, ctx: any) => {
    try {
      const prompt = typeof event?.prompt === 'string' && event.prompt.trim()
        ? event.prompt
        : getLastPiCliPrompt(ctx?.cwd || process.cwd(), currentSessionId);

      if (prompt) {
        currentTask = summarizePrompt(prompt);
      }

      await sendOfficeEvent('task.update', {
        session_id: currentSessionId,
        task: currentTask,
        status: 'working',
        pid: process.pid,
        ...clientIdentity
      });
    } catch {
      // safe fallback
    }
  });

  // 3. Hook: tool_call -> Intercept pemanggilan tool nyata (bash, read, write, edit, subagent)
  pi.on('tool_call', async (event: ToolEventPayload, ctx: any) => {
    try {
      const callId = event.toolCallId || `tc_${Date.now()}`;
      activeToolCalls.set(callId, Date.now());

      const toolName = event.toolName || 'tool';
      const input = event.input || {};

      // === DETEKSI REAL SUB-AGENT SPAWN ===
      if (toolName === 'subagent') {
        const subagentTask = input.task || input.workflow || 'Tugas delegasi subagent';
        const subagentKey = input.agent || input.lane?.key || `sub_${Date.now().toString(36)}`;
        const subPersona = getSubagentPersona(subagentKey);

        await sendOfficeEvent('team.register', {
          subagent_id: `${currentSessionId}_${subagentKey}`,
          parent_session_id: currentSessionId,
          parent_name: currentDisplayName,
          name: `${subPersona.name} · ${shortSessionSuffix(currentSessionId)}-${shortSessionSuffix(subagentKey)} [${subagentKey}]`,
          role: subPersona.role,
          avatar: subPersona.avatar,
          color: subPersona.color,
          cwd: ctx?.cwd || process.cwd(),
          model: input.model || 'inherited-model',
          task: subagentTask,
          ...clientIdentity,
          client_kind: 'subagent'
        });
      }

      // Catat tool call nyata
      await sendOfficeEvent('tool.call', {
        call_id: callId,
        session_id: currentSessionId,
        tool_name: toolName,
        input: input
      });
    } catch {
      // safe fallback
    }
  });

  // 4. Hook: tool_result -> Catat hasil eksekusi tool nyata & durasinya
  pi.on('tool_result', async (event: ToolEventPayload, _ctx: any) => {
    try {
      const callId = event.toolCallId || '';
      const startTime = activeToolCalls.get(callId) || Date.now();
      activeToolCalls.delete(callId);

      await sendOfficeEvent('tool.result', {
        call_id: callId,
        session_id: currentSessionId,
        tool_name: event.toolName,
        result: event.details || '(selesai)',
        is_error: !!event.isError,
        duration_ms: Date.now() - startTime
      });
    } catch {
      // safe fallback
    }
  });

  // 5. Hook: message stream -> tampilkan stream respons LLM realtime di bubble coffee.
  // Catatan: raw hidden chain-of-thought tidak dikirim; thinking_delta hanya jadi indikator aktivitas.
  pi.on('message_start', async (event: any) => {
    try {
      if (event?.message?.role !== 'assistant') return;
      liveResponseText = '';
      liveThinkingChars = 0;
      await publishLlmStream('status', 'LLM mulai menjawab…', false, true);
    } catch {
      // safe fallback
    }
  });

  pi.on('message_update', async (event: any) => {
    try {
      const update = event?.assistantMessageEvent;
      if (!update) return;

      switch (update.type) {
        case 'text_start':
          liveResponseText = extractAssistantVisibleText(update.partial) || liveResponseText;
          await publishLlmStream('response', liveResponseText || 'Respons mulai mengalir…', false, true);
          break;
        case 'text_delta':
          liveResponseText += update.delta || '';
          await publishLlmStream('response', liveResponseText || 'Respons mengalir…');
          break;
        case 'text_end':
          liveResponseText = update.content || liveResponseText;
          await publishLlmStream('response', liveResponseText, false, true);
          break;
        case 'thinking_start':
          liveThinkingChars = 0;
          await publishLlmStream('thinking', 'reasoning internal aktif…', false, true);
          break;
        case 'thinking_delta':
          liveThinkingChars += String(update.delta || '').length;
          await publishLlmStream('thinking', `reasoning internal mengalir (${liveThinkingChars} chars)…`);
          break;
        case 'thinking_end':
          await publishLlmStream('thinking', `reasoning internal selesai (${liveThinkingChars} chars)`, false, true);
          break;
        case 'toolcall_start':
        case 'toolcall_delta':
        case 'toolcall_end': {
          const toolName = extractToolCallName(event) || 'tool call';
          await publishLlmStream('tool', `Menyiapkan ${toolName}…`, false, update.type !== 'toolcall_delta');
          break;
        }
      }
    } catch {
      // safe fallback
    }
  });

  pi.on('message_end', async (event: any) => {
    try {
      if (event?.message?.role !== 'assistant') return;
      const finalText = extractAssistantVisibleText(event.message) || liveResponseText || 'Respons selesai.';
      liveResponseText = finalText;
      await publishLlmStream('response', finalText, true, true);
      await publishUsage(event.message);
    } catch {
      // safe fallback
    }
  });

  // 6. Hook: agent_end -> Turn selesai, agen kembali idle
  pi.on('agent_end', async () => {
    try {
      await sendOfficeEvent('session.heartbeat', {
        session_id: currentSessionId,
        status: 'idle',
        task: currentTask,
        pid: process.pid,
        ...clientIdentity
      });
    } catch {
      // safe fallback
    }
  });

  // 7. Hook: session_shutdown -> Sesi ditutup
  pi.on('session_shutdown', async () => {
    try {
      await sendOfficeEvent('session.end', {
        session_id: currentSessionId
      });
    } catch {
      // safe fallback
    }
  });

  // === PERINTAH /office — onboard mesin lain tanpa menyunting JSON ===
  if (typeof pi.registerCommand === 'function') {
    pi.registerCommand('office', {
      description: 'Kantor virtual: status | connect <token> | url <endpoint> | local | cloud | off | on | test',
      handler: async (args: string, ctx: any) => {
        const [verb = 'status', ...rest] = String(args || '').trim().split(/\s+/);
        // Explicit else, not `notify() || console.log()`: ui.notify returns undefined, so the
        // `||` form would print the same text to stdout and corrupt the TUI.
        const say = (text: string, level: any = 'info') => {
          if (typeof ctx?.ui?.notify === 'function') ctx.ui.notify(text, level);
          else console.log(text);
        };

        switch (verb) {
          case 'connect': {
            // `connect <token>` pakai endpoint bawaan paket; `connect <url> <token>` untuk hub lain.
            const [maybeUrl, maybeToken] = rest;
            const token = rest.length > 1 ? maybeToken : maybeUrl;
            const endpoint = rest.length > 1 ? maybeUrl : undefined;
            if (!token) return say('Pemakaian: /office connect <token> atau /office connect <url-hub> <token>', 'error');
            writeOfficeExtensionConfig({ ...(endpoint ? { endpoint } : {}), token, enabled: true });
            refreshOfficeConfig();
            const ok = await sendOfficeEvent('session.register', {
              session_id: currentSessionId, name: currentDisplayName, pid: process.pid, task: 'handshake /office connect',
              ...clientIdentity,
            });
            return say(ok
              ? `✅ Terhubung ke ${officeTelemetryTarget().endpoint} — mesin "${clientIdentity.machine_name}" masuk kantor.`
              : `⚠️ Config tersimpan, tapi kirim gagal (${officeTelemetryTarget().lastError}). Cek token/URL.`, ok ? 'info' : 'error');
          }
          case 'url': {
            if (!rest[0]) return say('Pemakaian: /office url <endpoint /api/event>', 'error');
            writeOfficeExtensionConfig({ endpoint: rest[0] });
            refreshOfficeConfig();
            return say(`🌐 Endpoint → ${rest[0]}`);
          }
          case 'local':
            writeOfficeExtensionConfig({ endpoint: DEFAULT_LOCAL_ENDPOINT, token: process.env.OFFICE_TOKEN || readRawOfficeConfig()?.token || '' });
            refreshOfficeConfig();
            return say(`🏠 Hub lokal → ${DEFAULT_LOCAL_ENDPOINT}`);
          case 'cloud':
            writeOfficeExtensionConfig({ endpoint: DEFAULT_CLOUD_ENDPOINT });
            refreshOfficeConfig();
            return say(`☁️ Worker cloud → ${DEFAULT_CLOUD_ENDPOINT}`);
          case 'off':
            writeOfficeExtensionConfig({ enabled: false });
            refreshOfficeConfig();
            return say('🔇 Telemetry kantor dimatikan di mesin ini.');
          case 'on':
            writeOfficeExtensionConfig({ enabled: true });
            refreshOfficeConfig();
            return say('🔊 Telemetry kantor aktif kembali.');
          case 'test': {
            const ok = await sendOfficeEvent('log.append', {
              session_id: currentSessionId, level: 'info', source: 'office-test', message: '🔔 Uji koneksi dari /office test',
            });
            const t = officeTelemetryTarget();
            return say(ok ? `✅ ${t.endpoint} menjawab.` : `❌ ${t.endpoint}: ${t.lastError || 'gagal'}`, ok ? 'info' : 'error');
          }
          default: {
            const t = officeTelemetryTarget();
            const origin = officeHubOrigin(t.endpoint);
            return say([
              '☕ ORCA24 office',
              `   endpoint : ${t.endpoint}${t.enabled ? '' : '  (telemetry OFF — /office on)'}`,
              `   dashboard: ${origin ?? '?'}`,
              `   token    : ${t.authed ? 'ya (bearer)' : 'BELUM ADA → /office connect <token>'}`,
              `   redaksi  : ${t.redacting ? 'aktif' : 'nonaktif'} — storage hub: ${t.hubStorage}`,
              `   mesin    : ${clientIdentity.machine_name} · ${clientIdentity.machine_id}`,
              `   kirim    : ${t.lastSentAt ? new Date(t.lastSentAt).toLocaleTimeString() : 'belum ada'}${t.lastError ? ` · terakhir gagal: ${t.lastError}` : ''}`,
            ].join('\n'));
          }
        }
      }
    });
  }

  // === CUSTOM TOOLS UNTUK KANTOR PI ===
  if (typeof pi.registerTool === 'function') {
    pi.registerTool({
      name: 'office_set_task',
      label: 'Set Status Tugas Kantor',
      description: 'Perbarui deskripsi tugas aktif Anda yang ditampilkan di dashboard kantor virtual.',
      parameters: {
        type: 'object',
        properties: {
          task: {
            type: 'string',
            description: 'Penjelasan singkat apa yang sedang Anda kerjakan sekarang (Bahasa Indonesia).'
          }
        },
        required: ['task']
      },
      execute: async (_toolCallId: string, params: { task: string }) => {
        currentTask = params.task;
        await sendOfficeEvent('task.update', {
          session_id: currentSessionId,
          task: currentTask,
          status: 'working',
          pid: process.pid,
          ...clientIdentity
        });
        return {
          content: [
            {
              type: 'text',
              text: `ok`
            }
          ]
        };
      }
    });

    pi.registerTool({
      name: 'office_announce',
      label: 'Umumkan ke Kantor',
      description: 'Kirim pengumuman atau pesan koordinasi ke seluruh tim di kantor virtual.',
      parameters: {
        type: 'object',
        properties: {
          message: {
            type: 'string',
            description: 'Pesan pengumuman untuk seluruh kantor.'
          }
        },
        required: ['message']
      },
      execute: async (_toolCallId: string, params: { message: string }) => {
        await sendOfficeEvent('log.append', {
          session_id: currentSessionId,
          level: 'info',
          source: 'announcement',
          message: `📢 [${currentDisplayName}]: ${params.message}`
        });
        return {
          content: [
            {
              type: 'text',
              text: `ok`
            }
          ]
        };
      }
    });
  }
}

export default officeExtension;
